spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_snippet
    username: user
    password: password
server:
  port: 9001

keycloak:
  keySetURI: "http://localhost:8080/realms/code_snippets/protocol/openid-connect/certs"