spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_snippet
    username: admin
    password: admin
  flyway:
    schemas: snippets_db
server:
  port: 9001
keycloak:
  keySetURI: "http://localhost:8080/realms/code_snippets/protocol/openid-connect/certs"